version: "3"

services:
  nestjs:
    container_name: nestjs
    build: .
    restart: always
    command: ["npm", "run", "start:dev"]
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  
  mongodb:
    container_name: mongodb
    restart: always
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local